### ISSUE TITLE
What about automocking

### ISSUE THREAD

**Issue by benzen** [tnwinc/Isolate#9]
This module seams to do something that i discovered with Facebook jest.
Hijack node/commonsjs require to pass in custom mock to the module undertest.
This is quite nice. Except that Jest commns with a lot of premaid choices, which i don't like.

I'm wondering if in this module, we could add something to build an auto mocking functionality.
Is this something your looking forward ?

**Comment by JamesMaroney** [comment]
Auto mocking is something that I thought would be a good idea when I started this project, but in my experience, it tended to not be as good as it sounded. with Isolate, you can use `mapType` to create really generic mocks based on type (for instance, I use this to mock all `function` dependencies with a fake that allows my test to inject the behavior)
I found that auto mocking took lots of overhead and still rarely gave me the a fake that was structured properly for my test.

Does this sound like it addresses your thoughts?

**Comment by JamesMaroney** [comment]
By the way, I still use Isolate every day, and for the last number of years, in an AMD setup. I built in support for node/commonjs early on (and have tests around it), but it has gotten very little exercise. 
If you do use Isolate, I would love to hear your feedback as to how it can best suit your needs. 
Thanks @benzen!

**Comment by benzen** [comment]
Thanks, i've played with jasmine testing for angular.
Things seems slow to write to me.

Having seen Jest recently it look new and shiny.
It's  was really tempting to use this with my experience.

I'm glad to have your feedback.

I think i will give isolate a try.

**Comment by benzen** [comment]
Since you have a _strong_ (doesn't mean it in the sens of not open, more in the sens of constructed) opinion on the matter, maybe you should add a note in the readme of this projet.

It will make it more reliable to find this information that to scan the issues, and closed issues.

Regards
